### ISSUE TITLE
Investigate user feedback via Signalr & Stdin/stdout on ACI

### ISSUE THREAD

**Issue by jjcollinge** [jjcollinge/terraform-deploy-to-azure#3]

**Comment by lawrencegripper** [comment]
As an MVP I looked at shell-in-a-box https://github.com/shellinabox/shellinabox

**Comment by lawrencegripper** [comment]
Or something more funky like this could be an option: https://github.com/joewalnes/websocketd

**Comment by lawrencegripper** [comment]
I think securing this nicely is going to be the interesting bit.

**Comment by jjcollinge** [comment]
Agree, we'll probably need to decide whether this is a blocker early on or whether we want to offer an API that can stream back the STDOUT/STDERR to the web app and stream basic input back to the Terraform CLI i.e. `yes, no, details`

**Comment by lawrencegripper** [comment]
The deployer would be responsible for starting terraform with the Stdin/stdout being encrypted then relayed to the users via Signalr.

**Comment by lawrencegripper** [comment]
@jjcollinge I've been playing a bit more in this space I think we can simplify things even more here to remove the need for signalr service. 

If the deployer container has a Public IP and hosts a websocket server then the client can connect directly to the deployer over the websocket and authentication can be handled by the pre-shared key setup when the deployer is created. 

What do you think?
