### ISSUE TITLE
Define SignalR protocol

### ISSUE THREAD

**Issue by jjcollinge** [jjcollinge/terraform-deploy-to-azure#8]
Define what messages need to be transferred between the client and the deployer service. This will at least include:
- Deployer requesting variables from client
- Client sending variables to the client
- Deployer streaming STDOUT/STDERR to client
- Client sending input to Deployer

**Comment by lawrencegripper** [comment]
Closed as moved to distributed model without server or signalr. Client SPA talks directly to WebSocket endpoint after creating it.
