### ISSUE TITLE
Investigate parsing and extracting variables from Terraform client side

### ISSUE THREAD

**Issue by jjcollinge** [jjcollinge/terraform-deploy-to-azure#9]
It would speed up the launch process if we could parse the terraform files in the client rather than in the deployer.

**Comment by jjcollinge** [comment]
Using [isomorphic git](https://github.com/isomorphic-git/isomorphic-git) with a [BrowserFS](https://github.com/jvilk/BrowserFS) backend we could clone the git repository, then use [hcl-to-json](https://www.npmjs.com/package/hcl-to-json) to convert all *.tf files into JSON and then merge them, extract the variables and then build the variables page dynamically.

**Comment by lawrencegripper** [comment]
closed by #10
